### PR TITLE
CI: Install deps from spec

### PR DESCRIPTION
**Pull request by wreis**
This proposes to install deps from setuptools spec, in order to avoid having duplicated places for setting dependencies.

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]
I like it! Why was `-I` necessary?

>   -I, --ignore-installed      Ignore the installed packages, overwriting them. This can break your
                              system if the existing package is of a different version or was
                              installed with a different package manager!

That sounds scary haha.

I'm not worried since it's just CI, but I am curious.

**Comment by wreis** [comment]
> Why was -I necessary?

pip was ignoring to collect `ruamel.yaml` for installation cause it was installed in some other packages site, but then failed to run tests raising ModuleNotFound. Indeed that is scary; do you think maybe the one we want actually is `--force-reinstall`?

**Comment by wreis** [comment]
`Requirement already satisfied: ruamel.yaml in /usr/share/miniconda/lib...`

**Comment by jameslamb** [comment]
so weird. But since it's only a testing dependency, it shouldn't cause any runtime issues. So I think it's ok to just say "well I don't know why this is happening but that fixed it". I don't see any risk from doing that.

**Comment by jameslamb** [comment]
oooo wait no it's not just a testing one! Sorry, got confused with this PR and `saturn-prefect-agent`

**Comment by wreis** [comment]
> "well I don't know why this is happening but that fixed it"

Yeah, dont know much cause it's GH Actions env; not entirely controlled by us. We could eventually move to a containers based CI setup for our projects.

> oooo wait no it's not just a testing one! Sorry, got confused with this PR and saturn-prefect-agent

It's reinstalling all deps there, overwriting whatever other from system; but it's only CI thing.

**Comment by jameslamb** [comment]
My worry now that we're thinking about this was that if a user did `pip install prefect-saturn` in a container where `ruamel.yaml` had already been conda installed, that they'd face the same ModuleNotFound problem you faced.

But I just tested that and it didn't happen:

```shell
conda create --name test-ruamel python=3.7
source activate test-ruaml

# not found
pip show ruamel.yaml

# not found
conda env export | grep ruamel

# fails
python -c "from ruamel import yaml"

# conda install
conda install -y ruamel.yaml

pip install .[tests]

# no issues
python -c "import prefect_saturn"
make unit-tests
```

So I think we can merge this and not worry about it :grinning:

**Comment by wreis** [comment]
Ok cool, thanks!

**Pull request merged**
