### PR TITLE
Bump development version

### PR DESCRIPTION
**Pull request by dotNomad**
- [X] passes `make lint`
- [X] adds tests to `tests/` (if appropriate)

## What does this PR change?

- Bumps version to `0.5.1.9000` for development

## How does this PR improve `prefect-saturn`?

> With this change, users can rely on the behavior that installations from source control will have a newer version than the newest release available on PyPI, but guaranteed to be older than the next release on PyPI.

### CODE REVIEW

**Comment by bhperry** [comment]
what is the need for this?

**Comment by dotNomad** [comment]
> what is the need for this?

It is the last step of the CONTRIBUTING document for a release. https://github.com/saturncloud/prefect-saturn/blob/main/CONTRIBUTING.md#releasing

I believe this is to prevent overwriting an install from GitHub due to a version comparison.

**Comment by jsignell** [comment]
Yeah so we talked about this in coffee I think. The point of adding a string to the end of the version is to have some indication that you are on a "dirty" version and that you are past the release. This comes up sometimes with pip where it might require > some version.

**Comment by bhperry** [comment]
That makes sense, but IMO it makes more sense to do that when main actually becomes "dirty". Right now it's exactly the same as the release, so changing the version seems strange to me.

**Comment by bhperry** [comment]
Fine with merging if this is what was agreed on though

**Comment by jsignell** [comment]
I think it's best to do it as part of the release just to make sure we don't forget.

**Review by bhperry — APPROVED** [review]
LGTM

**Pull request merged**
